# Generated by Django 3.2.3 on 2021-05-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('TG', 'Telegram'), ('IN', 'Instagram')], default='TG', max_length=2)),
                ('url', models.URLField()),
            ],
        ),
    ]
